# config.yml
logging:
  level: INFO                # уровень логирования: DEBUG/INFO/WARNING/ERROR/CRITICAL
  console_format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  telegram_format: '*%(levelname)s* %(message)s'
  tg_log: false               # включить/отключить отправку логов в Telegram-канал
  tg_error_log: false         # включить/отключить отправку ошибок проггерам


news_sources:
  - url: "https://wallpaper.com"
    tags: ["cars"]
  - url: "https://quto.ru"
    tags: ["cars"]
  - url: "https://kolesa.ru"
    tags: ["cars"]
  - url: "https://detailed.com"
    tags: [ "cars" ]
  - url: "https://motor.ru"
    tags: [ "cars" ]
  - url: "https://autonews.ru"
    tags: [ "cars" ]
  - url: "https://news.drom.ru"



filters:
  keywords:
    - "биткоин"
    - "нейросети"
    - "рынок акций"
