# config.yml
logging:
  level: INFO                # уровень логирования: DEBUG/INFO/WARNING/ERROR/CRITICAL
  console_format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  telegram_format: '*%(levelname)s* %(message)s'
  tg_log: false               # включить/отключить отправку логов в Telegram-канал
  tg_error_log: false         # включить/отключить отправку ошибок программистам


news_sources:
  - url: "https://wallpaper.com"
    topic: ["auto"]
  - url: "https://news.drom.ru/"
    topic: ["auto"]

  - url: "https://kolesa.ru"
    topic: ["cars"]
  - url: "https://detailed.com"
    topic: [ "cars" ]
  - url: "https://motor.ru"
    topic: [ "cars" ]
  - url: "https://autonews.ru"
    topic: [ "cars" ]


